name: Android CI (assembleDebug)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Gradle :app:assembleDebug
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: android-app
          arguments: :app:assembleDebug
          gradle-version: 8.0.2

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: RA-PDV-Wrapper-debug
          path: |
            **/build/outputs/**/*.apk
